### ISSUE TITLE
Set rules for the final open-ended question in the review form.

### ISSUE THREAD

**Issue by donika-kraeva** [Dentacoin/review-platform#10]
At the end of each review form, there is a field requesting a written comment from the patient as a summary of his impressions. In most cases this feedback is the most valuable to the dentist. At the moment you can write "dfgdf" or "Thanks" with no problem at all. Thus we have hundreds of reviews with a written comment "thanks" e.g.. We should make this a bit more difficult. Suggestions:
- The comment should be at least 20 words and at least 80 characters.
- The comment shouldn't be the same as any other comment on the platform. 

Opinions? Other suggestions?

**Comment by YouPlusWe** [comment]
Depends on how much you'd like to invest in this:

Words + Characters limit is a must and is super easy to implement.

Then comes the gibberish detection. It's usually done by a AI/ML approach. I found this thing:
https://github.com/buggedcom/Gibberish-Detector-PHP
which uses machine learning and Markov chains. Looks promising, but has to be tested / learned properly and there still will be a chance that users may receive strange results ( gibberish text is considered good and vice-versa ).

**Comment by donika-kraeva** [comment]
Let's start with the words/characters limit.
@neptox Opinion on the gibberish detection please.

**Comment by YouPlusWe** [comment]
http://glandings.youpluswe.com/test/index.php -> Tester for the gibberish detector. Write some text and hit the submit button. Works pretty good with longer texts.
Have in mind it has to be trained per language (now it's trained with the entire The Adventures of Sherlock Holmes novel in English)

**Comment by tscherrie** [comment]
Let's go with the word limit for now and see how it works. We can take it a step further later, if needed.
I'm fine with 20 words and at least 80 characters.

**Comment by YouPlusWe** [comment]
Done.
@donika-kraeva You cna find the error message in the translation system -> page.dentist.review-form-text-short

My thoughts on the limits -> 80 characters are way too less for 20 words. I think we should increase the characted limit or decrease the word limit. The ratio should be 5:1 ( http://www.wolframalpha.com/input/?i=average+english+word+length )

**Comment by donika-kraeva** [comment]
@YouPlusWe Alright then: 100 characters, 20 words

**Comment by YouPlusWe** [comment]
@donika-kraeva Done
