### ISSUE TITLE
Implement Google Analytics Tracking code

### ISSUE THREAD

**Issue by donika-kraeva** [Dentacoin/review-platform#11]
... both on DentaVox and on the Review Platform. The code is sent via email.

**Comment by YouPlusWe** [comment]
Access granted.
Let me know if you need me to set up events & custom dimensions.

**Comment by YouPlusWe** [comment]
No reply. If custom events & codes are required, a new task will be created.

**Comment by donika-kraeva** [comment]
Move it to complete, please. When we decide for custom events, we will create a new task. Thanks.
