### ISSUE TITLE
Upgrade the DCN rewards server to suport the latest geth version.

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#13]

**Comment by YouPlusWe** [comment]
@neptox I'm currently sending the required headers. Please let me know once you update geth, so I can test again.

**Comment by tscherrie** [comment]
I'll update it today and let you know

**Comment by donika-kraeva** [comment]
@YouPlusWe @neptox If this has been done already, please move it to Completed.
