### ISSUE TITLE
Handle NO PEERS cases when sending a transaction.

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#14]
From time to time there are no available peers in the Ethereum node and we can't send the transaction, so the user gets this:

Error: Returned error: can't fetch trie key d0a76832edc6ca00ff4fc8e2e22137a21db16f09bc6761ae3804ab0181c77cd0: no suitable peers available

Those "peer outages" can last from 1-2 minutes to 1-2 hours.

**Comment by YouPlusWe** [comment]
@donika-kraeva UX & cost wise we have 3 options here:
- tell the user we can't send this transaction right now and **ask him to try again** (super easy / super bad UX)
- tell the user we can't send this transaction right now and **we'll keep trying, but s/he has to keep the browser tab open** ( easy / not the best UX ). We can add a countdown timer for the next retry or something similar too keep the attention.
- tell the user we can't send this transaction right now but **we'll do so automatically when there are peers available so s/he can close the browser tab** . ( will take moderate effort / decent UX ). This means creating an automated transaction queue  system that keeps track of transactions ( successful / no peers ) and user intents ( withdraw from VOX / get registration bonus / write a review ). The system will auto-retry "no peer" transactions and will complete the user intents (i.e. if the user wanted to write a review, it'll submit the review after the transaction is successful ) and send them emails ( i.e. hey, your withdraw is complete / your review was posted / your registration reward was claimed ).

@neptox will constant retrying do some harm to the server?

**Comment by donika-kraeva** [comment]
@YouPlusWe The third option seems like the most reasonable one from a user's point of view. @neptox Opinion please.

**Comment by YouPlusWe** [comment]
We now have a centralized transaction system ( TRP & Vox ). When a user performs a DCN related action we send the transaction and return a TX hash. If the ETH network is down or there's some other issue with the transaction we tell the user we'll let him know when the transaction it complete via email.
A crob job checks all transactions and auto-retries them if necessary.
Users have Transaction History tabs with statuses and links to etherscan.io in both TRP & Vox.
In the CMS there's a new Transactions page which allows searching by user id, ETH address and TX hash. Each user profile displays a list with all transactions.

@donika-kraeva please check "CMS -> Email Templates -> Transaction completed" when you have the chance. This is the email tempalte that gets sent once we confirm a transaciton.

**Comment by donika-kraeva** [comment]
Alright. @neptox Please check, test and confirm if you haven't yet.

**Comment by tscherrie** [comment]
@donika-kraeva @YouPlusWe I agree with the third option. And retry sending txs is no problem for the server!

**Comment by YouPlusWe** [comment]
OK, that's already implemented. You can check CMS > Transactions for a list of all transactions along with status and retry count. Retying works with incrementing exponential intervals 10min > 20min > 40min >1h 20 min > 2h 40min ....
