### ISSUE TITLE
Send rewards to dentists for Trusted reviews

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#2]
Send rewards to dentists for Trusted reviews from their patients ( only when the patient was invited by the dentist ). 
Make sure we have the dentist's DCN address before we allow him/her to send invites.

**Comment by YouPlusWe** [comment]
Suggestions:
- give the Dentists the same invite options ( affiliate link, Gmail / Yahoo / Hotmail ) as the patients

**Comment by donika-kraeva** [comment]
@YouPlusWe Confirmed. Let's implement your suggestion as well.

**Comment by YouPlusWe** [comment]
That's done, but:
- How much DCN should we send to the dentist ( currently 5000 DCN )? @neptox 
- There's currently only one Email Template for "New review", even if it's a trusted review. This way the dentist won't know that s/he just received a reward for having a review from an invited user. Should I create another template for this? @donika-kraeva

**Comment by donika-kraeva** [comment]
@YouPlusWe Yes, please. We need another template for review written after an accepted invitation.

**Comment by tscherrie** [comment]
@YouPlusWe let’s start with symbolic 5000 DCN at the beginning

**Comment by YouPlusWe** [comment]
@neptox Done
@donika-kraeva I've created a new template ( the last in the list ) and copied the text from the "regular" review template. Feed free to edit it wheny ou have thr chance.
