### ISSUE TITLE
Validate Dentists' addresses

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#3]
When registering a Dentist:
- ask for address
- get a list of Dentistry related places near this place from Google Places for Business
- ask him/her to pick one of those

In the dentist's profile:
- allow him/her to chnage the address using the same flow

**Comment by donika-kraeva** [comment]
@YouPlusWe Confirmed.

**Comment by YouPlusWe** [comment]
@donika-kraeva I've implemented this in the profile info section, but I'm having some doubts about the UX. Can you please test it and let me know what you think.
