### ISSUE TITLE
Allow patients to invite friends to join the platform.

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#4]
- Add new subpage in Profile - Invite Friends
- Ask the user to provide us with DCN address beofre being able to invite friends ( no way to reward them otherwise )
- Provide 3 options: Get a link / Enter email addresses manually / use Gmail, Hotmail and Yahoo
- Option 1 - we provide the user with an affiliate link and allow him to select & copy it and also share it over the social networks.
- Option 2 - we present a simple text field + submit button - you enter email address submit and we send the Invites
- Option 3 - the user provides access to his/her account. We scan it for emails and provide a list. The user picks items from the list and we send the Invites
- When a user registers via invitation link, we reward the Invitor with DCNs

**Comment by YouPlusWe** [comment]
I'll need accounts in:
- https://cloud.google.com/ ( uses Google Account )
- https://developer.yahoo.com/ ( uses Yahoo Account )
- https://apps.dev.microsoft.com/

**Comment by YouPlusWe** [comment]
How many DCNs should the reward be?

**Comment by donika-kraeva** [comment]
@YouPlusWe Everything in regards to the flow is correct here. All developer accounts are created as well. I will clarify the DCN values and come back to you.

**Comment by YouPlusWe** [comment]
@donika-kraeva @neptox please let me know of the reward amount. I've set it to 5000 for now.

@donika-kraeva please take a look at: "CMS > Email Templates > Invitation accepted (Dentist) and Invitation accepted (Patient)". Those templates are sent to the person who invites. The first template is for when a dentist sent the invitation ( congrats, your patient Joshua just registered, expect a review soon ), and the second one - for when a patient sent the invitation ( your friend Jacob just registered, we've sent you a reward ).

Registration rewards are send only when Patients invite ( but Dentist will receive reward when they get a Trusted review ). The rewards are visible in the History section of the profile:
![image](https://user-images.githubusercontent.com/16322895/33722569-ff47e992-db72-11e7-9566-90294561c5b2.png)

**Comment by donika-kraeva** [comment]
Good. I am fine with the history and the templates. I am trying to get the values :)

**Comment by donika-kraeva** [comment]
@YouPlusWe Change of plans in order to avoid senseless registrations with no real action on the platform: The inviter will receive his reward if his friend has accepted his invitation and has written a review. Please tell me how much time you will need to modify this.

On DentaVox, that would mean after the friend has filled at least one questionnaire.

**Comment by YouPlusWe** [comment]
@donika-kraeva The change is implemented. Please take a look the the email templates:
- Invitation accepted (Patient)
- Invitation reward sent (Patient)
The first one is sent to you when someone invited by you registers in the platform ( no reward is sent ).
The second one is send to you when someone invited by you writes his/hers first review ( now you get your reward ).
