### ISSUE TITLE
Provide Dentists with website code for reviews widget

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#5]
- Add new subpage in Profile
- Inside show a JS code and a preview of the widget
- Show instructions on how to use the code

**Comment by YouPlusWe** [comment]
@neptox your thoughts on this code? I'm thinking of a JS code like:
<script async src="...file on our website with som parameters..."></script>
Which will display the necessary widget and will allow responsive design.

This is the standard approach, but it can't be used directly in Wordpress, which is the most popular CMS right now.

Plan B is to provide them with iframe tag which can be used in Wordpress, but will have fixed width / height.

What do you think about this issue? We can also provide both options or develop a WP plugin.

**Comment by tscherrie** [comment]
For now, let's use both options (script and iframe) and promote it as "flexible for your website" and "for Wordpress"

**Comment by YouPlusWe** [comment]
@donika-kraeva What about the content of the widget? 
Should we just show a e-card ( photo, name, address, phone, email ) and the overall rating
OR
E-card + detailed rating
OR
E-card + detailed rating + list of reviews

**Comment by donika-kraeva** [comment]
@YouPlusWe We need a list with all the reviews received by this dentist; no e-card of the dentist, just the name and his reviews below. My suggestion for each review:
- Patient name + date
- Overall rating
- Written comment

Trusted reviews should be shown first. Can we actually offer both options to dentists: 1) showing only trusted reviews; or 2) showing all reviews? 

@neptox @YouPlusWe  Opinion on these matters?

**Comment by YouPlusWe** [comment]
We can give them both options. You have to decide if it's worth it.
PS: Should we show the dentist's reply (if the dentist replied to a comment)

**Comment by donika-kraeva** [comment]
Both options, please.

**Comment by donika-kraeva** [comment]
As for the replies: Can we show just an indication that there is a reply (a simple text "1 reply") but the reply itself to be shown only after clicking? 

P.S. Did I explain this clear?

**Comment by YouPlusWe** [comment]
@donika-kraeva 
@neptox 
Here's a first version of the iFrame approach:
https://reviews.dentacoin.com/en/widget/10/a85760c18454c096e178c85776637749/1

This can be embedded into any website by using:

`<iframe style="width: 100%; height: 50vh" src="https://reviews.dentacoin.com/en/widget/10/a85760c18454c096e178c85776637749/1"></iframe>
`

You can see it posted in a WordPress blog page here:
http://logtis.youpluswe.com/logtis-ihr-partner-fur-kompetente-field-services/
and here:
http://logtis.youpluswe.com/ ( scroll down to see it )

Looking forward to your feedback

**Comment by YouPlusWe** [comment]
+ one more example, thanks to @SergeyUshakov : 
https://www.dentacoin.com/neraboti/

**Comment by YouPlusWe** [comment]
The other embed option is ready too. Here's a sample code:

```
<div id="trp-widget"></div>
<script type="text/javascript" src="https://reviews.dentacoin.com/js/widget.js"></script>
<script type="text/javascript">
TRPWidget.init("https://reviews.dentacoin.com/en/widget/10/a85760c18454c096e178c85776637749/1");
</script>
```

Here it is embedded in an empty page:
https://reviews.dentacoin.com/bla.html

@donika-kraeva Please let me know what you think about my suggestion:
I think we should provide TRP users with the option to pick a color when getting the widget code and to use this color instead of the main blue color. This way if you have, say, green website, you'll be able to get an equally green widget.

And I'll go ahead and add a new page in dentsts' profiles where they'll be able to get a code for their websites.

**Comment by YouPlusWe** [comment]
https://reviews.dentacoin.com/en/profile/widget

Please take a look and provide me with feedback

PS: Make usre you are logged in with Dentist account

**Comment by donika-kraeva** [comment]
I like the idea of setting different colors to fit the website of the dentist - let's go for it.

Apart from that, I have mainly some problems with the design. There are too many elements. What we could do:

- As the button "Show entire review" actually leads to all the reviews of this dentist, and not to this particular one - then we don't need it below each review but only ones. E.g. in the headline "Dentaprime City - Гранд мол's reviews on Dentacoin Trusted Review Platform -> See all reviews"

- Another option would be if "Show entire review" leads to this particular review but it's not shown with a button, but with a plain text + link which could be positioned directly below the written comment. No boxes. 

- About the reply from the dentist: If there is no option to hide the reply itself but only show that there is "1 reply >>", then we better not show it at all in my opinion. Because most of the dentists would like to at least say "Thank you" which will make the widget too crowded. 

@neptox Any word on this?

**Comment by YouPlusWe** [comment]
@donika-kraeva I can make the buttons lead to the exact review. So shoud I:
- Replace the huge boxy button with a text link
- Hide the replies and just add "1 reply >>" which will also be a link to the review in TRP?
