### ISSUE TITLE
Allow patients to have multiple Personal Dentists

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#6]
- When I write review to a Dentist - he/she becomes my personal Dentist
- This applies only to the first 3 dentists I write reviews to
- If I want to write a review to 4th dentist, I'll receive message that I'm not allowed to and a suggestion to ask him for an Invite
- We'll add another section in Invite Patients - Invite requests. There we'll show requests from Patients with the option to Approve / Reject those
- Once rejected, a patient can't ask for invitation from the same dentist

**Comment by donika-kraeva** [comment]
@YouPlusWe Everything is okay here. One remark on the last point: "Once rejected, a patient can't ask for invitation from the same dentist" -> Theoretically, the user could at some point become a patient to this dentist. So the patient should receive a message like: "You cannot ask for an invitation as your request has already been rejected from XYZ (the name of the practice). If you believe that this has been a mistake, please get in touch with XYZ and ask them to send you an invitation". Therefore, the dentist should still be able to send an invitation to this patient even if he has rejected him once.

**Comment by YouPlusWe** [comment]
Done, there's a "User requests" section in the dentists profiles which appears only if they have requests from patients.
Patients can send requests ONLY if they try to write a review on a detnist who is not their personal dentist AND have already written reviews on 3 such dentists.
