### ISSUE TITLE
Translators' accounts in CMS

### ISSUE THREAD

**Issue by YouPlusWe** [Dentacoin/review-platform#9]
Allow translators accounts to be created who will have access only to the translation menu.

**Comment by YouPlusWe** [comment]
@donika-kraeva should we add a "language from" and "language to" fields for each translator? Otherwise all translators will have access to all languages.

**Comment by donika-kraeva** [comment]
@YouPlusWe Yes, please. Each translator should only be able to translate to a particular language.

**Comment by YouPlusWe** [comment]
+ on @SergeyUshakov 's request:
a dropdown /checkbox list should be added for chosing which parts of the system should be accessible to translators ( TRP / dentavox / CMS )

**Comment by donika-kraeva** [comment]
Okay, it makes sense.

**Comment by YouPlusWe** [comment]
Done, please check and confirm

**Comment by donika-kraeva** [comment]
Confirmed.
